version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: wagtail
    versions:
    - "2.12"
    - 2.12.1
    - 2.12.2
    - 2.12.3
