# Local/Dev
version: "3"
services:
  web:
    image: frojd/geo-widget-web
    build: .
    volumes:
      - ./:/app
    ports:
      - "8085:8000"
    depends_on:
      - db
    links:
      - db
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    env_file: web.env
  db:
    image: postgis/postgis:13-3.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
