# Generated by Django 3.1.13 on 2021-09-28 15:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailgeowidget.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('geopage_nospatial', '0003_auto_20210928_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streampage',
            name='body',
            field=wagtail.core.fields.StreamField([('map_struct', wagtail.core.blocks.StructBlock([('address', wagtailgeowidget.blocks.GeoAddressBlock()), ('map', wagtailgeowidget.blocks.GeoBlock(address_field='address', hide_latlng=True))], icon='user'))]),
        ),
    ]
