# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:19
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geopage', '0004_auto_20170327_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopagerelatedlocations',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_locations', to='geopage.GeoPage'),
        ),
    ]
