# Generated by Django 4.2.23 on 2025-08-14 04:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                ("location", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="StandardPageWithLeaflet",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Search powered by Nominatim",
                        max_length=250,
                        null=True,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="StandardPageWithLeafletAndZoom",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Search powered by Nominatim",
                        max_length=250,
                        null=True,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=250, null=True)),
                ("zoom", models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="StandardPageWithZoom",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                ("location", models.CharField(blank=True, max_length=250, null=True)),
                ("zoom", models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="StreamPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("map", 0),
                            ("map_leaflet", 1),
                            ("map_struct", 4),
                            ("map_struct_leaflet", 7),
                            ("map_struct_with_zoom", 10),
                            ("map_struct_leaflet_with_zoom", 12),
                        ],
                        block_lookup={
                            0: ("wagtailgeowidget.blocks.GoogleMapsBlock", (), {}),
                            1: ("wagtailgeowidget.blocks.LeafletBlock", (), {}),
                            2: (
                                "wagtailgeowidget.blocks.GeoAddressBlock",
                                (),
                                {"required": True},
                            ),
                            3: (
                                "wagtailgeowidget.blocks.GoogleMapsBlock",
                                (),
                                {"address_field": "address"},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("address", 2), ("map", 3)]],
                                {"icon": "user"},
                            ),
                            5: (
                                "wagtailgeowidget.blocks.GeoAddressBlock",
                                (),
                                {"geocoder": "mapbox", "required": True},
                            ),
                            6: (
                                "wagtailgeowidget.blocks.LeafletBlock",
                                (),
                                {"address_field": "address"},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("address", 5), ("map", 6)]],
                                {"icon": "user"},
                            ),
                            8: (
                                "wagtailgeowidget.blocks.GeoZoomBlock",
                                (),
                                {"required": False},
                            ),
                            9: (
                                "wagtailgeowidget.blocks.GoogleMapsBlock",
                                (),
                                {"address_field": "address", "zoom_field": "zoom"},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("address", 2), ("zoom", 8), ("map", 9)]],
                                {"icon": "user"},
                            ),
                            11: (
                                "wagtailgeowidget.blocks.LeafletBlock",
                                (),
                                {"address_field": "address", "zoom_field": "zoom"},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("address", 2), ("zoom", 8), ("map", 11)]],
                                {"icon": "user"},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
